server:
  port: 7002
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false #是否将eureka注册写不写都是一样的但是建议将其注册
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    hostname:  eureka7002.com #eureka的服务端名字