server:
  port: 8085
spring:
  application:
    name: cloud-provider-8085
  cloud:
    consul:
      discovery:
        hostname: 127.0.0.1
        service-name: ${spring.application.name}
        port: 8500