server:
  port: 3344
spring:
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git:
         strict-host-key-checking: false
         clone-on-start: true
         uri: https://github.com/iosyyy/config.git
         search-paths:
            - config
         username: 626797813@qq.com
         password: jinghong12345..
      label: master
eureka:
  client:
   service-url:
    defaultZone: http://eureka7001.com:7001/eureka/

