
spring:
  application:
   name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
server:
  port: 9092
management:
  server:
    port: 9092
  endpoints:
    web:
      exposure:
        include: '*'