server:
  port: 8001
spring:
  application:
    name: payment-hystrix-8001

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true #是否将eureka注册写不写都是一样的但是建议将其注册
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: paymentHystrix
    prefer-ip-address: true